### ISSUE TITLE
mimeType

### ISSUE THREAD

**Issue by pontusab** [guhungry/react-native-photo-manipulator#18]
mimeType is always PNG. is that a known issue?

**Comment by guhungry** [comment]
Okay, I will check it asap.

**Comment by guhungry** [comment]
Ok, I found the bug in [MimeUtils toExtension] in [ios-photo-manipulator](https://github.com/guhungry/ios-photo-manipulator) which was fixed in [ios-photo-manipulator@63ae5d2](https://github.com/guhungry/ios-photo-manipulator/commit/63ae5d234f0fe18049f6c5255a60afda29b6ea87#diff-cebb987e54e177b26d56233ab27ead8b) since 25 March 2019. But I haven't published new version until now.

Can you run `pod update` and verify that ```WCPhotoManipulator``` is the ```1.0.0``` version in ```Podfile.lock```

**Comment by pontusab** [comment]
Works great now! Thanks!
