### ISSUE TITLE
(Android) Immutable bitmap passed to Canvas constructor

### ISSUE THREAD

**Issue by bruno02100** [guhungry/react-native-photo-manipulator#221]
When using batch method, this error is thrown. "Immutable bitmap passed to Canvas constructor"

**Comment by guhungry** [comment]
@bruno02100 What are the operations for batch so I can reproduce?

**Comment by bruno02100** [comment]
I made a quick fix on a fork. https://github.com/bruno02100/react-native-photo-manipulator, but overlays on Android are not visible.

**Comment by guhungry** [comment]
It seems the bug related to do overlay many times. I suspect that after overlay it make image immutable. I'll fix it asap.

**Comment by guhungry** [comment]
@bruno02100 Can you try with version 1.2.3

**Comment by bruno02100** [comment]
Thanks for the fix! Doesn't crash anymore, but the overlays are not showing either 😅 I guess thats another bug, will try to find the root cause.

**Comment by bruno02100** [comment]
Note that on iOS the overlays are properly added.

**Comment by guhungry** [comment]
> Thanks for the fix! Doesn't crash anymore, but the overlays are not showing either 😅 I guess thats another bug, will try to find the root cause.

Is it because of this line https://github.com/bruno02100/react-native-photo-manipulator/commit/31b8faa0a4ff6ea113bccff3575c82187e7b3a2e#diff-d819789614b8ff569ff2afad11100d0ade681aecb8a54fc753f728e4f32b01d8L80-R80?
With fix 1aa84f3fab7ae46a2fc48e94f30fb0e63ce3e8e1, above line should be reverted since image.copy() will overlay the copy not the image itsself that why there is no overlay with your initial fix.

If you have any problem please let me know

**Comment by guhungry** [comment]
If you still have problem please reopen the issue.
