### ISSUE TITLE
It will be great if support base64 image.

### ISSUE THREAD

**Issue by moustaphadiakhate** [guhungry/react-native-photo-manipulator#27]
Have it a solution to make it support base64 image ?

**Comment by guhungry** [comment]
No direct support for base64 image source yet but for a quick hack you can [write](https://github.com/itinance/react-native-fs#writefilepath-string-contents-string-position-number-encoding-string-promisevoid) file from base64 with [react-native-fs](https://github.com/itinance/react-native-fs) and use that result for this library. and then [unlink](https://github.com/itinance/react-native-fs#unlinkfilepath-string-promisevoid) the file after processed by this library

PR is welcome though.

**Comment by guhungry** [comment]
@moustaphadiakhate Or do you mean send base64 result back together with result path?

If so, it is doable but it will be breaking change due to return value change.
Note for me.
* iOS from UIImage to base64 string - https://stackoverflow.com/questions/11251340/convert-between-uiimage-and-base64-string
* Android from Bitmap to base64 string - https://stackoverflow.com/questions/9224056/android-bitmap-to-base64-string

**Comment by moustaphadiakhate** [comment]
No the first one. Giving  the base64 in input image. Yes it's a nice suggestion using react-native-fs. I will do that. Thanks you !

**Comment by guhungry** [comment]
Glad that it helps.

**Comment by guhungry** [comment]
Hi @moustaphadiakhate,
Base64 encoded images support has been added in [v1.7.0](https://github.com/guhungry/react-native-photo-manipulator/releases/tag/v1.7.0)

You can use with
```
data:image/png;base64,iVBORw...
```
