### ISSUE TITLE
Add scale for overlay image

### ISSUE THREAD

**Issue by akrueger90** [guhungry/react-native-photo-manipulator#273]
Hey, 

it would be great if we could scale overlay images. I take photos and overlay them. But on different devices the photos have different dimensions. It would be cool if I could automatically scale the overlay to 10% width and length of the base image.

**Comment by guhungry** [comment]
What is the image type of overlay static (require() in javascript) or dynamic (from url)?
If it was a static you can have different image scale for different screen density by add suffix to filename @2x @3x  @4x (https://reactnative.dev/docs/images)

But I think it would make api more complicate due to need to find correct scale by themself instead of let React Native handle it.

**Comment by akrueger90** [comment]
It is a static image. I use this as a watermark for all photos taken. 
I will use the image suffix. 
Just thought it would be good to use your crop method for the overlay as well.

**Comment by guhungry** [comment]
@akrueger90 for crop + watermark you can use batch() because it crop image and then apply batch operations as specified (add watermark or print text)
