### ISSUE TITLE
null is not an object error

### ISSUE THREAD

**Issue by hamncheez** [guhungry/react-native-photo-manipulator#499]
Hi, like the title says, I'm getting this error when trying to use any of the public methods. I'm importing it correctly with modern ES6 best practices. Any suggestions?

![image](https://user-images.githubusercontent.com/9424895/151893521-9034d1a1-96ad-4760-8196-76159f05fe8e.png)

**Comment by andre-luiz1997** [comment]
@hamncheez   Have you found any solution to this Issue? I am developing an app in Expo with react-native: 0.64.3 and still getting the same error. Seems that is something related to auto-linking. Any updates, @guhungry

**Comment by andreiwow2** [comment]
I have same issue with .crop

**Comment by andreiwow2** [comment]
@andre-luiz1997 @hamncheez You have to do `pod install` inside the iOS folder

**Comment by sameert89** [comment]
Does it even work with Expo? If there is a linking issue that means we cannot use it with expo.

**Comment by guhungry** [comment]
this library doesn't work with expo due to this is react native native module (not pure javascript)

**Comment by guhungry** [comment]
I am working on the expo-photo-manipulator, but I can't give a timeline for when it will be published.

**Comment by guhungry** [comment]
> @hamncheez Have you found any solution to this Issue? I am developing an app in Expo with react-native: 0.64.3 and still getting the same error. Seems that is something related to auto-linking. Any updates, @guhungry

Hi @hamncheez @andre-luiz1997 and @sameert89, 
It may be too late, but this library does work with Expo without any modification at least on the latest Expo 51.
But here are the catches
1) It won't work and never will on Expo Go (Since it does not support the native modules)
2) You need to [create a development build](https://docs.expo.dev/develop/development-builds/create-a-build/) to install this library as native module
3) Install dependencies with `npx expo install react-native-photo-manipulator` or `yarn expo install react-native-photo-manipulator`
4) Build and run the app
compiled on android
<img width="574" alt="Screenshot 2567-08-10 at 23 57 16" src="https://github.com/user-attachments/assets/894f7a25-af89-4b3b-9abb-ef0f501fda67">

compiled on ios
<img width="364" alt="Screenshot 2567-08-10 at 23 59 09" src="https://github.com/user-attachments/assets/236dc024-55b5-499a-a71b-47cd0a3d75bf">

works on android emulator
<img width="160" alt="Screenshot 2567-08-11 at 00 01 46" src="https://github.com/user-attachments/assets/b62f225b-3a69-42e4-a8b8-2b13bdea34a3">

Cheers
